---
title: "Simulation"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(rvest)

set.seed(1)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

```

Load key packages and source necessary files.
```{r}
library(tidyverse)
source("source/sim_mean_sd.R")
```


We can "simulate" by running our function.

```{r}
sim_mean_sd(n_subj = 400)
```


Can I "verify" the Central Limit Theorem?

First with a `for` loop

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(30)
}

output |> 
  bind_rows() |> 
  ggplot(aes(x = mu_hat)) +
  geom_density()
```


Try to repeat with a `map` statement


```{r}
sim_results_df =
  expand_grid(
    iter = 1:100,
    sample_size = c(30, 60, 90, 120)
  ) |> 
  mutate(
    results = map(iter, sim_mean_sd)
  ) |> 
  unnest(results)
```




















